services:
  docs:
    image: qa_web_app_local_docs
    container_name: qa_web_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./qa_web_app:/app/qa_web_app:z
    ports:
      - '9000:9000'
    command: /start-docs
